### ISSUE TITLE
Log files not always being produced when KSF code run in competition mode

### ISSUE THREAD

**Issue by JennyLynnFletcher** [srobo/competition-simulator#175]

**Comment by PeterJCLaw** [comment]
I suspect this was an issue with buffering of the output and the team not incrementing the simulation. The latter is still a potential issue, though there's not a lot we can do about it.
Since we're now using wrapped stream handling which flushes on every write, buffering shouldn't be an issue.
Closing as this doesn't feel useful without a reproduce.
We can re-open this with more details if it reappears.
