### ISSUE TITLE
Live scoring

### ISSUE THREAD

**Issue by antoinepetty** [srobo/competition-simulator#18]
Implement a way to score each round automatically (and display this on screen?)

This will involve at least:
- checking that we can detect cases where an object is "inside" or "touching" another object (at least in the 2D arena sense, possibly as well as implementing the three-corner rule or similar)
- recording changes to that state, either as a log of change events or as snapshots of the new state on change, or similar so that we can replay the scoring later; likely we'd want match-timestamps here to help line up to the animation

I suggest that we probably want a separate Supervisor to handle the scoring, if Webots supports having more than one.
Note that this scoring Supervisor may need to communicate with the arena Supervisor (see #216), so it may make sense for them to be the same process.

**Comment by PeterJCLaw** [comment]
Tying the match running to SRComp's HTTP API would likely be somewhat complicated on a couple of fronts:
- SRComp is designed around consuming fixed data from a git repo, so writing data to it via the API would be quite a big change. Not sure if that's what you had in mind though
- for SR2020 we ended up actually running the simulations of the matches slightly ahead of the broadcast in order to ensure that they worked as expected and for our own organisational simplicity; we're unlikely to change this, meaning that the API (at least the public facing one) wouldn't necessarily actually be in sync with the matches being run

Instead I think we're more likely to head down the route of having the supervisor "robot" doing a bunch of the match coordination side of things and then outputting a structured log (with timestamps) of what happened so we can feed that through the system.

There is of course plenty of room to feed those output logs into SRComp to expose the information to API consumers (would need work in SRComp, however as an extension to the existing match score files I can see this fitting reasonably well).

**Comment by PeterJCLaw** [comment]
Note for picking this up -- I suspect that this might be easier after we've fixed #83 since that also involves interpreting the positions of items in the world.

**Comment by WillB97** [comment]
The sr2021 game has a secondary supervisor running the territory_controller. Currently each time a zone is claimed a line is printed to stdout with the station code, claimant and simulation time. It just needs to be converted into a form that srcomp can accept.
